#You can remove any of these fields to have the program use the defaults. If you
#delete the whole file, it will be restored to default. If you screw up formatting
#one of the entries, errors WILL occur.
message:
    #The red title at the top of the login screen.
    title: Hello!
    #A list of text to be displayed under the title.
    #There must be at least one line here or the default will be used.
    contents:
    - This server requires user authentication.
    - If this is your first time put in your password,
    - and then confirm it in the confirm dialogue.
    - Otherwise, put in your registered password and click login.
    - Have fun!
login:
    #The message shown above the register form.
    register: Fill out the form to register for the server.
    #The text in each of the login lables. The last 2 are only used
    #in the registration form. Each of these is adjacent to a
    #corresponding textbox.
    username: "Username:"
    password: "Password:"
    confirm: "Confirm password:"
    email: "Email (Optional):"
    #The text used in the buttons at the bottom of the screen.
    registerbutton: Register
    loginbutton: Login
    exitbutton: Exit
#These are errors that are not in xAuth (always supported)
errors:
    nopassword: You must fill out a password!
    passwordmismatch: Passwords don't match!
    #in the error/success screen, there is a continue button.
    #if you have your players report seeing a "Downloading Terrain"
    #screen after the button gets closed, just turn this to
    #false and it should be fixed.
    displaybutton: true
#How things are registered and/or logged in. If you use xAuth, then put in
#xauth for the best results, if you use anything else, just put in the command
#any instance of {password} will be replaced with the given password and {email}
#will be replaced with the given email (register only). In addition, {user} will
#be replaced with the player's name. So, a possible thing that could be put in would
#be "/login {password}" and "/register {password} {email}" In addition, you can
#repurpose the {email} and {password} by changing their description above and then
#putting them in a different place.
#
#If either one of these is used, then xAuth is needed. If you aren't using xAuth, then
#I have no way of detecting if the player has registered so there will be a "click to register"
#button.
modes:
    login: xauth
    register: xauth